rabbitmq:
  image: rabbitmq:management
  ports:
  - 5672:5672
  - 15672:15672
redis:
  image: redis:4
  ports:
   - 6379:6379
cassandra:
  image: cassandra:3
  ports:
  - 9042:9042
  - 9160:9160
cassandrasetup:
  image: cassandra:3
  links:
    - cassandra
  command: bash -c "sleep 40 && echo Creating keyspace && cqlsh cassandra -e \"CREATE KEYSPACE IF NOT EXISTS soeventstore WITH REPLICATION={'class':'SimpleStrategy','replication_factor':1}\" && sleep infinity"