server:
  port: 8861
spring:
  application:
    name: sales-order-edit-eventstore-service
  data:
    cassandra: 
      keyspace-name: soeventstore 
      schema-action: create-if-not-exists
      pool:
        max-queue-size: 2000
eventstore:
  consumer:
#    - http://localhost:8871/v1/events
    - http://localhost:8873/v1/events
    
