server:
  port: 8861
spring:
  application:
    name: sales-order-edit-eventstore-service
  data:
    mongodb:
      database: sales-order-edit-eventstore-service-db  
eventstore:
  consumer:
#    - http://localhost:8871/v1/events
    - http://localhost:8873/v1/events
